dist: xenial

language: python

install:
  - pip install numpy
  - pip install tox

script:
  - tox -r

jobs:
    include:
        - env: TOXENV=coverage
          python: 3.8

        - env: TOXENV=py38
          python: 3.8
